# Service account for permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opencost.serviceAccountName" . }}
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml . | indent 4) $ }}
{{- end }}