# Expose the cost model with a service
#
# Without a Prometheus endpoint configured in the deployment,
# only opencost/metrics will have useful data as it is intended
# to be used as just an exporter.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencost.fullname" . }}
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.uiPort }}
      targetPort: {{ .Values.service.uiPort }}
      protocol: TCP
      name: {{ include "opencost.fullname" . }}-ui
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ include "opencost.fullname" . }}
  selector:
    {{- include "opencost.selectorLabels" . | nindent 4 }}